### ISSUE TITLE
New NBS Bioinformatician at UHPL!

### ISSUE THREAD

**Issue by erinyoung** [eilbecklab/Utah-DOH-newborn-screening#2]
@EliasOnAWS is our new NBS bioinformatician at UPHL. 

I'm tagging him here so he knows this exists. He may be asking you questions.

**Comment by keilbeck** [comment]
Good to know. Look forward to working with you. Dave Sant and Nicole Ruiz were the main developers. I can give overview, maybe dig up an old poster or 2.
